from dever00 import LeagueOfLegends,Time,Jogador

if __name__ == "__main__":

    L1 = LeagueOfLegends("Gwen","Top",-1)
    L2 = LeagueOfLegends("Lulu","Suporte",11)
    T1 = Time("Loud", "N/A", 0, "1", 1, 15)
    T2 = Time("Pain", "N/A", 0, "1", 2, 12)
    J1 = Jogador("Robo","Jax","Top",18,17,"Loud")
    J2 = Jogador("Titan","Lucian","ADC",16,23,"Pain")

    L2.set_nivel(15)
    print("\nPersonagem")
    print("\n====================================")
    print("\nNome:",L1.get_nome())
    print("Rotas:",L1.get_rotas())
    print("Nivel:",L1.get_nivel())
    print("\n====================================")
    print("\nPersonagem")
    print("\n====================================")
    print("\nNome:",L2.get_nome())
    print("Rotas:",L2.get_rotas())
    print("Nivel:",L2.get_nivel())
    print("\n====================================")
    print("\nTime")
    print("\n====================================")
    print("\nNome:",T1.get_nome())
    print("Tier:",T1.get_Tier())
    print("Posicao:",T1.get_posicao())
    print("Pontos:",T1.get_pontos())
    print("\n====================================")
    print("\nTime")
    print("\n====================================")
    print("\nNome:",T2.get_nome())
    print("Tier:",T2.get_Tier())
    print("Posicao:",T2.get_posicao())
    print("Pontos:",T2.get_pontos())
    print("\n====================================")
    print("\nJogador")
    print("\n====================================")
    print("\nNome:",J1.get_nome())
    print("Campeoes:",J1.get_campeoes())
    print("Rotas:",J1.get_rotas())
    print("Nivel:",J1.get_nivel())
    print("Idade:",J1.get_idade())
    print("Time:",J1.get_time())
    print("\n====================================")
    print("\nJogador")
    print("\n====================================")
    print("\nNome:",J2.get_nome())
    print("Campeoes:",J2.get_campeoes())
    print("Rotas:",J2.get_rotas())
    print("Nivel:",J2.get_nivel())
    print("Idade:",J2.get_idade())
    print("Time:",J2.get_time())
    print("\n====================================")
    print(J1.validar_idade())
    print(J2.validar_idade())

